### ISSUE TITLE
[BUG] Thut's Elevators Entity Bug

### ISSUE THREAD

**Issue by Hexeption** [magmafoundation/Magma#105]
**Describe the bug**
Casting error when trying to create an elevator

**To Reproduce**
1. Download Thut's Elevators
2. Start Server
3. Use linking item to select an area 
4. Look at console

**Expected behavior**
To create an elevator

**Info (please complete the following information):**
- Mod Name:  Thut's Elevators
 - Mod Version:  6.1.6
 - Magma Version:  0e43213
 - OS: Windows

**Additional context**
![yFqFl73Mpv 1](https://user-images.githubusercontent.com/4052647/79901697-1ed37200-8408-11ea-9941-c4f945843fa8.png)
[latest.log](https://github.com/magmafoundation/Magma/files/4512015/latest.log)

**Comment by kwright02** [comment]
The root of this seems to be on the bukkit side

**Comment by kwright02** [comment]
This error is purely due to the way Thut handles the lift entities, and it's not compatible with Craftbukkit's entity conversion handling. It tries to cast the EntityLift to a Living entity, which it cannot be, but it is an EntityLivingBase because it is movable, This will require some special fixing

**Comment by kwright02** [comment]
Labeled as incompatible for now.
