### ISSUE TITLE
[Issue] Magma + SkyFactory4 4.1.0 + itzg Docker

### ISSUE THREAD

**Issue by Fireant456** [magmafoundation/Magma#121]
**Describe the issue**
A clear and concise description of what the bug is: Server will crash at start when running Magma with SkyFactory4 on itzg's Docker container see log for crash message.

**Info (please complete the following information):**
- Mod Name: SkyFactory4
 - Mod Version: 4.1.0
 - Magma Version: 2798a77
 - OS: CentOS 7 Docker using https://github.com/itzg/docker-minecraft-server

**Additional context**
Add any other context about the problem here:

[latest.log](https://mclo.gs/sCzF8rG)

**Comment by Fireant456** [comment]
Waiting on Itzg to reply to see if I am passing the JVM variables correctly. My docker configs can be viewed on that [github issue.](https://github.com/itzg/docker-minecraft-server/issues/525)

**Comment by Fireant456** [comment]
As documented in https://github.com/itzg/docker-minecraft-server/issues/525 we have resolved the issue with the environment variables passing to JVM. Still receiving the same crash as shown in the last linked latest.log

**Comment by kwright02** [comment]
Please try this again with the latest magma release and see if the issue persists

**Comment by kwright02** [comment]
Basically what I've found is that for whatever reason it's not finding that particular library at runtime. I'm not sure what's causing this on that docker image and will need to work with you for further testing. Until you're available for that I'm going to close this issue since it's isolated to that specific instance.
