### ISSUE TITLE
[BUG] No BrewerInventory in InventoryOpenEvent

### ISSUE THREAD

**Issue by Sn0wStorm** [magmafoundation/Magma#284]
**Describe the bug**

Using `getInventory()` in the `InventoryOpenEvent` when opening a Brewing Stand inventory returns a `CraftInventory` instead of a `CraftInventoryBrewer`

**To Reproduce**

Listening to the `InventoryOpenEvent` do `event.getInventory().toString()` and then open a Brewing Stand

**Expected behavior**
Output should be `org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryBrewer`
but it is `org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory`

This means that `event.getInventory()` is not a `BrewerInventory` even though on Spigot it is and should be.

Strangely, doing `((BrewingStand) event.getInventory().getHolder()).getInventory())`
**does** in fact return a `CraftInventoryBrewer`

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: Newest: HEAD-5db17b2
 - OS: Unix

**Additional context**
This issue prevents the Brewing Stand from working as a destiller in my plugin Brewery

https://github.com/DieReicheErethons/Brewery/issues/334

**Comment by kwright02** [comment]
When utilizing events, the parameters are generalized for general events. For example, on a blockBreakEvent `event.getBlock()` will not return the unique class of the block that you just broke. It will return a generic block class that holds the material and other basic information. You would need to cast it like `((Stone) event.getBlock())` to get the Stone class. The same thing goes with the inventoryOpenEvent where the inventory type is generalized to CraftInventory because there are dozens of unique inventory types. Given this, you should always typeSafe cast like you show above `((BrewingStand) event.getInventory().getHolder()).getInventory())` this is not a bug. Another more simple way to get the CraftBrewerInventory would be to do this: `((CraftBrewerInventory) event.getInventory())`

**Comment by Sn0wStorm** [comment]
Problem is, you can't even cast it to a BrewerInventory because it is not an instance of it.

```
Inventory inv = event.getInventory();
if (player == null || !(inv instanceof BrewerInventory)) return;
```
https://github.com/DieReicheErethons/Brewery/blob/c8a7a56ab95e5c2730179a75f0ec1772923f9fb1/src/com/dre/brewery/listeners/InventoryListener.java#L37

Returns, because inv is not instanceof BrewerInventory.
