### ISSUE TITLE
[BUG]Autoclicker crashes server

### ISSUE THREAD

**Issue by Fnndxgh** [magmafoundation/Magma#374]
A clear and concise description of what the bug is:
ClickMachines Autoclicker Crashes the server. It is no longer possible to restart the server without it crashing again as long as the block is still in the world file.

![grafik](https://user-images.githubusercontent.com/79112745/107992538-3a33ed00-6fd9-11eb-9d47-7facfbad591e.png)

[crash-2021-02-15_21.42.36-server.txt](https://github.com/magmafoundation/Magma/files/5984024/crash-2021-02-15_21.42.36-server.txt)

1. Place Autoclicker

**Info (please complete the following information):**
- Mod Name:ClickMachine
 - Mod Version: -1.12.2-1.2.0
 - Magma Version: b2a81d7
 - OS: Windows 10

**Comment by LegitSoulja** [comment]
Could you provide crash report? It’ll tell you the exact location of this block. Start the server whitelisted, it shouldn’t crash. Use worldedit and send command /pos1 x,y,z and /pos2 x,y,z

Optionally, can be fixed with mcedit. I have the same issue with hoppers and some mods like openblock blockbreakers, it will crash your server. I’ve banned a couple of things, and also have auto rollback protection in-case of crashes. 

Hopefully these issues are fixed, along with BlockBreakEvent.

**Comment by Fnndxgh** [comment]
First of all its not possible to start the server even if no-one joins also I already removed the block myself with mcedit. But still thx for ur help
