### ISSUE TITLE
[BUG] Resonant Rise 5 Disconnect Error

### ISSUE THREAD

**Issue by Diamondman121314** [magmafoundation/Magma#47]
**Describe the bug**
When using the modpack Resonant Rise 5, there's an error between the client and server when connecting, preventing on from fully connecting to the server. This does not happen on when using Forge alone.

**To Reproduce**
1. Attempt to join the server

**Expected behavior**
I expect that I should be able to join the server without any problem, like I am able to do so on vanilla.

**Screenshots**

**Info (please complete the following information):**
 - Mod Name: Resonant Rise 5 Modpack
 - Mod Version: 5.0.0-pre.2
 - Magma Version: f5bbe59 aka build 21 on Jenkins
 - OS: kubuntu @ 18.10 (ubuntu/cosmic) < (on original testing)

**Additional context**
[Server Log](https://gist.githubusercontent.com/Diamondman121314/5339b00c18913167dc1036dae35b9c08/raw/be3615b4a1823022cd2860b93e6383a013d17c85/gistfile1.txt)
[Server Log #2](https://pastebin.com/izDXV3v2)
[Client Log](https://gist.githubusercontent.com/Diamondman121314/6cc0b4396cf398cff8a9208b08800fcf/raw/f785950f23f88961fc5e9bbc23ed39ae63127f00/gistfile1.txt)

Also, @HappyGoKaboom, here you go.

**Comment by HappyGoKaboom** [comment]
This turns out to be a mod conflict with the Librarian mod that Classy mod depends on, apparently Librarian mod doesn't work well with RedstoneFlux.

Removed those mods and it works.

This was tested with the latest versions of Magma the crash occurs when the client joins the server and the client gets disconnected.

Tested the server with forge and with forge + spongeforge and it works with those mods, just not if we use magma.

With the mods removed worked fine one day but ran into another client disconnect issue the next day I will get logs sorted during the week with some investigation to identify any other mod resulting in the problem and narrow it down for you, will open a separate issue for that one as it seems to be something else.

**Comment by kwright02** [comment]
Closing as OP said issue was resolved.
