### ISSUE TITLE
[API] Magma API

### ISSUE THREAD

**Issue by Hexeption** [magmafoundation/Magma#73]
Please submit ideas below that you would like to see implemented into Magma

**Comment by UeberallGebannt** [comment]
**simple Bungeecord send method** 

so that you dont have to use plugin messaging channels if you want to connect using spigot

**Comment by RednedEpic** [comment]
A _decent_ item and block API that works with both vanilla materials and modded materials; preferably without the use of enums ❤️

**Comment by kwright02** [comment]
@RednedEpic When you say without using enums, what are you suggesting to be used in place of them?

**Comment by RednedEpic** [comment]
> @RednedEpic When you say without using enums, what are you suggesting to be used in place of them?

Probably public static final fields for vanilla items and blocks and some kind of static getter (from identifier) so modded blocks and items can be retrieved, like the Sponge BlockTypes and ItemTypes classes. I say without enums because you can’t add new values to enums without doing some extremely hacky stuff that at the very minimum is buggy and has unintended side effects.

**Comment by Jay113355** [comment]
Perhaps a way to access the modlist of the client.

**Comment by kwright02** [comment]
@RednedEpic I think part of the reason you can't do modded items currently is because of that exact reason. Stylistically Enums are the way to go for something like block type references, but we could experiment with a system that revolves around the identifier rather than an enum. Maybe a class that you use to retrieve the item based on the identifier?

**Comment by RednedEpic** [comment]
> @RednedEpic I think part of the reason you can't do modded items currently is because of that exact reason. Stylistically Enums are the way to go for something like block type references, but we could experiment with a system that revolves around the identifier rather than an enum. Maybe a class that you use to retrieve the item based on the identifier?

Yeah that's what I was thinking. This is just a mock up but I think something like this could work:

```java
public class MagmaItems {
    public static final MagmaItem APPLE = MagmaItemRegistry.REGISTRY.getItem(Identifier.of("minecraft", "apple"));
    // ..blablabla

    public static MagmaItem getItem(Identifier identifier) {
        return MagmaItemRegistry.REGISTRY.getItem(identifier);
    }
}
```
This is just a mock and likely not what the final result would (or should) look like at all, but just something that hopefully better explains what I'm trying to say. The only major issue I'm really thinking of when it comes to this is a way to somehow make it easier for developers when it comes to supporting both modded environments and vanilla environments, since something like this would require them to use a try/catch block or abstraction every time they want to use a material somewhere (with modded support of course). 

Ultimately this will require some more thought. One idea I thought of was doing something like PaperLib, where a lightweight library is instead used, and the usage of MagmaItem or material is determined there. MagmaItems would be constructed directly from Materials on vanilla, while on Magma or a modded environment, it's constructed from the forge item/block registry instead.

**Comment by Hexeption** [comment]
> Perhaps a way to access the modlist of the client.

This is already implemented in the PlayerAPI https://github.com/magmafoundation/Magma/blob/master/src/main/java/org/magmafoundation/magma/api/PlayerAPI.java

**Comment by kwright02** [comment]
closing for now as the discussion has died.
