### ISSUE TITLE
[BUG] Worldedit Forge ID support lacking

### ISSUE THREAD

**Issue by GuusLieben** [magmafoundation/Magma#82]
**Describe the bug**
Worldedit (Spigot edition) does support the reading of ID's when using Magma, however it cannot pattern match it to an existing block.
Tested with both vanilla WorldEdit and FastAsyncWorldEdit.

**To Reproduce**
1. Use a tool with //info bound to it to read the ID of any modded block
2. Use //set {id} on an area
3. See error

**Expected behavior**
Expected Magma to handle Forge ID matching to blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/10957963/75613079-ed39db00-5b29-11ea-8df8-90e1395edb60.png)

**Info (please complete the following information):**
- Plugin Name: FastAsyncWorldEdit
 - Plugin Version: any
 - Magma Version: Magma-776897d-server
 - OS: Windows 10 Pro / Ubuntu Server 18.04 LTS

**Comment by Hexeption** [comment]
Its recommend to use the Forge version of world edit

**Comment by GuusLieben** [comment]
Due to integrationist with other plugins that's not possible in our case (PlotSquared, Arceon, BuildTools)

**Comment by kwright02** [comment]
Then it seems that you’re sol at the moment

**Comment by kwright02** [comment]
@Hexeption This should be closed

**Comment by GuusLieben** [comment]
Disagreed, the issue is still present preventing me from using worldedit dependant plugins

**Comment by kwright02** [comment]
Overruled, this should be closed because it's not a magma issue. It's up to whatever software you want to use to support magma, not the other way around. We can't force your plugins to used modded blocks, they have to have handled for it. Therefore this is not a bug/issue within magma itself. Use moded world edit or try voxel sniper or something. Worldguard is not world edit dependant, and I don't know of any plugins that are strictly dependant on it. Regardless, there should be plenty of alternatives, moded or not.

@Hexeption this should be closed
