### ISSUE TITLE
Will Magma ever be updated to 1.16 or any newer minecraft version? [Question]

### ISSUE THREAD

**Issue by Beyondo** [magmafoundation/Magma#94]
Minecraft is having a very huge nether update in 1.16. So are you going to support that version or will you stay at 1.12.2 forever? Just asking so I know if I should base my server on Magma or not. p.s I really do like your software but you could at least update its version every 3 months or so, being outdated is no fun and we miss a lot of cool things. Also I'm new so I don't know if you are already doing updates, however, it's been a very long time since 1.12.2 (almost 3 years) so that's why I'm asking this.

**Comment by Birbe** [comment]
1. The bug label should not be used for this. It should only be used for functionality that is built into Magma that does not function as it should.
2. "An update every 3 months" is extremely difficult if not impossible for a hybrid server. Even Forge has taken longer than 3 months to update to a new version. 
3. Most hybrid servers (servers combining two platforms) typically stay on one version because it can take a really long time to iron out all bugs. To date, there really hasn't been a "stable" server that works seamlessly immediately, although Magma is doing very well and seems to be one of the best we've seen.

**Comment by kwright02** [comment]
@Hexeption this should be closed or at least removed from the bugs category

**Comment by Hexeption** [comment]
1.15 is in development
